version: "3"
services:
  app:
    build:
      context: .
    image: iclinic-prescriptions
    volumes:
      - ./:/var/task
    depends_on:
      - db
    links:
      - db
  db:
    image: mysql:8.0.21
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3307:3307"
    expose:
      - 3307
    environment:
        MYSQL_ROOT_PASSWORD: shtshDHDH42142
        MYSQL_DATABASE: prescriptions
        MYSQL_USER: iclinic
        MYSQL_PASSWORD: shtshDHDH42142
        MYSQL_TCP_PORT: 3307
    volumes:
      - /var/lib/mysql
volumes:
  my-db:
