version: "3"
services:
  app:
    build:
      context: .
    image: iclinic-prescriptions
    volumes:
      - ./:/var/task
    entrypoint:
      - ""
    ports:
      - "9200"
      - "9300"
    depends_on:
      - db
      - dynamo
    links:
      - db
      - dynamo
  db:
    image: mysql:8.0.21
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3307:3307"
      - "3306:3306"
    expose:
      - 3307
      - 3306
    environment:
        MYSQL_ROOT_PASSWORD: jyjyjrtJKJKUJK123123
        MYSQL_DATABASE: prescriptions
        MYSQL_USER: iclinic
        MYSQL_PASSWORD: jyjyjrtJKJKUJK123123
        MYSQL_TCP_PORT: 3307
    volumes:
      - /var/lib/mysql
  dynamo:
    image: amazon/dynamodb-local
    ports:
      - "8000"
volumes:
  my-db:
