version = 0.1
[dev]
[dev.deploy]
[dev.deploy.parameters]
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Env=\"Dev\" ProjectName=\"IclinicPrescriptions\" SSMPrefix=\"/dev/db/\""
stack_name = "iclinic-api"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1qutbj8rdskmx"
s3_prefix = "sam-app"
