name: Iclinic Prescriptions API

on:
  pull_request:
    types: [opened, synchronize]
  workflow_dispatch:
    inputs:
      name:
        description: 'Manual or automatic execution'
        default: 'Manual or automatic execution'
        required: true
  push:
    branches: [develop, main, master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker-compose build
    - name: testing with MySQL
      run: |
        echo 'starting machine'
        docker-compose up -d
        echo 'machine started'
        echo 'pausing: waiting for mysql to come available'
        ./scripts/wait-until "docker-compose exec -T -e MYSQL_PWD=jyjyjrtJKJKUJK123123 db mysql -D prescriptions -e 'select 1'" 15
        echo 'un-pausing: mysql is now available'
    - name: Run tests
      run: docker-compose run --rm app py.test --cov-report term
